<?php
$CONFIG = array (
  'passwordsalt' => 'P8aN24HAuP89MGd5fPD6GIw02P9aFT',
  'secret' => 'wV+Va0kA6f03iJqFdVWh1D729qY07e4DhcPIu9wCdx/H17mb',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '192.168.77.161',
    2 => 'nextcloud',
    3 => 'nextcloud',
  ),
  'datadirectory' => '/var/ncdata',
  'overwrite.cli.url' => 'https://nextcloud/',
  'dbtype' => 'mysql',
  'version' => '12.0.1.5',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_ncadmin',
  'dbpassword' => 'NWbczfYmxba20vU5ZfFyftgNYa26Ac',
  'installed' => true,
  'instanceid' => 'ocv615oyovm6',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
    'password' => 'dMqHpjz#xdkiT41oY#C7Kf1zxfHbX*dXa6S',
  ),
  'htaccess.RewriteBase' => '/',
  'loglevel' => 2,
);
